version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=DEBUG